
<html>
<head>
  <title></title>
  <body background="blue">
  </body>
  </head>
<center>
<h2>Lista de usuarios</h2>

<a href="<?php echo APP_URL."usuarios/add"; ?>">Agregar usuarios</a>

<table width="200" border="10" >

  <tbody>

  
    <tr>
    
      <th><p style = "color: red;">ID</p></th>
      
      <th><p style = "color: red;">Email</p></th>
      
      <th><p style = "color: red;">Username</p></th>
      
      <th><p style = "color: red;">Password</p></th>
      
      <th><p style = "color: red;">Status</p></th>
      
      <th><p style = "color: red;">Accion</p></th>
    </tr>
    
    <?php foreach($this->usuarios as $usuario): ?>

    
    <tr>
    
      <td><?php echo $usuario["id"]; ?></td>
      
      <td><?php echo $usuario["email"]; ?></td>
      
      <td><?php echo $usuario["username"]; ?></td>
      
      <td><?php echo $usuario["password"]; ?></td>
      
      <td><?php echo $usuario["status"]; ?></td>
      
      <td>
      
          <a href="<?php echo APP_URL."usuarios/edit/".$usuario['id']; ?>">Editar</a> |
           
          <a href="<?php echo APP_URL."usuarios/delete/".$usuario['id']; ?>">Eliminar</a>
      
      </td>
      
    </tr>
    
    <?php endforeach; ?>
    
  </tbody>
</table>
</center>
 